### PR TITLE
Add a proposal for the tech stack and tooling

### PR DESCRIPTION
**Pull request by Leonils**
Any comment ? 

Especially TOML is not an obvious choice, but it seems rather good for configuration files. 

We already discussed rust a little

### CODE REVIEW

**Review by DarkPitoune — APPROVED** [review]
100% agree for 1 and 2
I don't have enough XP to make relevant comments on 3 and 4

**Comment by GauthierDoppler** [comment]
Same, I don't have enough technical experience to comment the 3rd and 4th points ! 
But agree on 1&2 

Do you have any strategies to deploy the CLI ? I don't really know how it works in this cases

**Comment by Leonils** [comment]
> deploy the CLI

You mean how we will distribute it? I think at first we will just release the built artifacts on github for each platform, so the users can download it an place it where they want. 

If we want to go further, it will depend on the target. We may use https://crates.io/crates/cargo-bundle to bundler into .dev, .app, .msi. 

Would that be enough ?

**Comment by Leonils** [comment]
The last one is quite commonly accepted in the rust community. 

The 3rd one is much more impactful however: from node we are quite used to use async code only as soon as we need concurrency, as node is single threaded. Rust do not have this limitation. However, async rust is quite hard compared to synchronous rust. This book is a good start : https://rust-lang.github.io/async-book/. The "Why async" explain the main things to consider when choosing a model.

**Review by GauthierDoppler — APPROVED** [review]

**Pull request merged**
